name: Build Front & Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy frontend'
        required: true
        default: 'develop'

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.branch == 'master' && 'prod' || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          ref: ${{ github.event.inputs.branch }}
