name: Test

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        run: echo ${{ github.ref_name }}
